### ISSUE TITLE
UWP Problem

### ISSUE THREAD

**Issue by RamazanBIYIK** [ishrakland/ListViewWithSubListView#1]
Hi @ishrakland I can make it work on android but couldn't make it on UWP. I can see their replacement in UWP page but couldn't see the text. Why is that happening?

**Comment by ishrakland** [comment]
this works on android and iOS but i didn't test it on UWP as i dont have the environment . Could you please add a screenshot? .  Try to set textColor to black for example and test again.

**Comment by RamazanBIYIK** [comment]
Hi again, Now it fixed when i reset my computer. It works fine on UWP too. I am closing issue. Good Work!!

**Comment by ishrakland** [comment]
Ok, Good !!

**Comment by ishrakland** [comment]
Could you Star this repo please?
